version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  groupchat_user:
    image: sinsung6722/groupchat_user:v1
    depends_on:
      - kafka
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  groupchat_file:
    image: sinsung6722/groupchat_file:v1
    depends_on:
      - kafka
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  groupchat_externalsystem:
    image: sinsung6722/groupchat_externalsystem:v1
    ports:
      - "8086:8086"
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: "sinsung6722-toygroupchat"
      AWS_REGION_CODE: "ap-northeast-2"


  groupchat_message:
    image: sinsung6722/groupchat_message:v1
    depends_on:
      - kafka
    ports:
      - "8084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  groupchat_room:
    image: sinsung6722/groupchat_room:v1
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker


  groupchat_collecteddata:
    image: sinsung6722/groupchat_collecteddata:v2
    depends_on:
      - kafka
    ports:
      - "8087:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  groupchat_gateway:
    image: sinsung6722/groupchat_gateway:v1
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: docker


  groupchat_frontend:
    image: sinsung6722/groupchat_frontend:v3
    ports:
      - "3000:3000"