server:
  port: 8088

spring:
  application:
    name: gateway

  config:
    use-legacy-processing: true

  main.allow-bean-definition-overriding: true

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"

logging:
  level:
    root: WARN
    toykiwi.gateway.custom: DEBUG

# JWT 설정 및 인증을 위한 Public & Private 키 경로
jwt:
  issuer: toygroupchat.io
  expire-after-seconds: 36000
  public.key: classpath:rsa.public.key

---

spring:
  profiles: host

  cloud:
    gateway:
      routes:
        - id: userAuthCheck
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/sanityCheck/authenticationCheck
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}


        - id: messageSanityCheck
          uri: http://localhost:8084
          predicates:
            - Path=/api/message/sanityCheck
          filters:
            - RewritePath=/api/message/(?<segment>.*), /${segment}

        - id: message
          uri: http://localhost:8084
          predicates:
            - Path=/api/message/**
          filters:
            - RewritePath=/api/message/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter


        - id: roomSanityCheck
          uri: http://localhost:8085
          predicates:
            - Path=/api/room/sanityCheck
          filters:
            - RewritePath=/api/room/(?<segment>.*), /${segment}

        - id: room
          uri: http://localhost:8085
          predicates:
            - Path=/api/room/**
          filters:
            - RewritePath=/api/room/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter

---

spring:
  profiles: docker

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}

---

spring:
  profiles: kubernates

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}
