server:
  port: 8088

spring:
  application:
    name: gateway

  config:
    use-legacy-processing: true

  main.allow-bean-definition-overriding: true
  # cloud.gateway.enabled: false

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            # allowCredentials: true

logging:
  level:
    root: WARN
    toykiwi.gateway.custom: DEBUG
    org.springframework.security: DEBUG

# JWT 설정 및 인증을 위한 Public & Private 키 경로
jwt:
  issuer: toygroupchat.io
  expire-after-seconds: 36000
  public.key: classpath:rsa.public.key
  private.key: classpath:rsa.private.key

---

spring:
  profiles: host

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}

---

spring:
  profiles: docker

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}

---

spring:
  profiles: kubernates

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /${segment}
